set_false_path -from [get_pins cpuresetn_reg/C] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[36]/CLR}]
set_false_path -from [get_pins cpuresetn_reg/C] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[0]/CLR}]
set_false_path -from [get_pins cpuresetn_reg/C] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[12]/CLR}]
set_false_path -from [get_pins cpuresetn_reg/C] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[41]/CLR}]
set_false_path -from [get_pins cpuresetn_reg/C] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[6]/CLR}]
set_false_path -from [get_pins cpuresetn_reg/C] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[20]/CLR}]
set_false_path -from [get_pins cpuresetn_reg/C] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[23]/CLR}]
set_false_path -from [get_pins cpuresetn_reg/C] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[35]/CLR}]
set_false_path -from [get_pins cpuresetn_reg/C] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[2]/CLR}]
set_false_path -from [get_pins cpuresetn_reg/C] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[17]/CLR}]

set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/rptr_gray_reg[3]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/DST_CDC_DLY_2_BRANCH.rptr_gray_to_src_clk_syn_1_reg[3]/D}]
set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/rptr_gray_reg[0]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/DST_CDC_DLY_2_BRANCH.rptr_gray_to_src_clk_syn_1_reg[0]/D}]
set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/rptr_gray_reg[1]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/DST_CDC_DLY_2_BRANCH.rptr_gray_to_src_clk_syn_1_reg[1]/D}]
set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/rptr_gray_reg[2]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/DST_CDC_DLY_2_BRANCH.rptr_gray_to_src_clk_syn_1_reg[2]/D}]

set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/MEM_RESET_BRANCH.MEM_RESET_LOOP[6].fifo_mem_reg[6][2]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[2]/D}]
set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/MEM_RESET_BRANCH.MEM_RESET_LOOP[1].fifo_mem_reg[1][6]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[6]/D}]
set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/MEM_RESET_BRANCH.MEM_RESET_LOOP[2].fifo_mem_reg[2][35]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[35]/D}]
set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/MEM_RESET_BRANCH.MEM_RESET_LOOP[7].fifo_mem_reg[7][23]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[23]/D}]
set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/MEM_RESET_BRANCH.MEM_RESET_LOOP[1].fifo_mem_reg[1][31]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[31]/D}]
set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/MEM_RESET_BRANCH.MEM_RESET_LOOP[6].fifo_mem_reg[6][10]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[10]/D}]
set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/MEM_RESET_BRANCH.MEM_RESET_LOOP[3].fifo_mem_reg[3][3]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[3]/D}]
set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/MEM_RESET_BRANCH.MEM_RESET_LOOP[7].fifo_mem_reg[7][26]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[26]/D}]
set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/MEM_RESET_BRANCH.MEM_RESET_LOOP[4].fifo_mem_reg[4][34]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[34]/D}]
set_false_path -from [get_pins {U_VGA_TOP/U_AFIFO/MEM_RESET_BRANCH.MEM_RESET_LOOP[4].fifo_mem_reg[4][0]/C}] -to [get_pins {U_VGA_TOP/U_AFIFO/RS_VR/FWD_VR_BRCH.FWD_RST_BRCH.fwd_reg_pld_reg[0]/D}]
